version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: vuttr
      POSTGRES_USER: vuttr
      POSTGRES_PASSWORD: vuttr
      POSTGRES_DB: vuttr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
