version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: vuttr
      POSTGRES_PORT: 5432
      POSTGRES_USER: vuttr
      POSTGRES_PASSWORD: vuttr
      POSTGRES_DB: vuttr
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: vuttr
      POSTGRES_USER: vuttr
      POSTGRES_PASSWORD: vuttr
      POSTGRES_DB: vuttr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
